# Generated by Django 4.2.7 on 2024-04-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0088_return_order_stock_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='return_product',
        ),
    ]
