# Generated by Django 4.2.7 on 2024-04-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0090_coupon234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon234',
        ),
    ]
