# Generated by Django 4.2.7 on 2024-04-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0091_delete_coupon234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
    ]
