# Generated by Django 4.2.7 on 2024-04-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstcryapp', '0093_coupon_description_coupon_discount_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
